module.exports = {
  apps: [
    {
      name: '3d-lms-api',
      script: 'dist/src/index.js',
      cwd: './server',
      instances: 2,
      exec_mode: 'cluster',
      wait_ready: true,
      listen_timeout: 10000,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '../logs/api-error.log',
      out_file: '../logs/api-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: '3d-lms-queue-worker',
      script: 'npm',
      args: 'run start:worker',
      cwd: './server',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '../logs/queue-worker-error.log',
      out_file: '../logs/queue-worker-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: '3d-lms-official-site',
      script: 'node',
      args: '.output/server/index.mjs',
      cwd: './website',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: '3002',
        // 「进入平台」按钮跳转地址，改成你的主平台正式域名
        NUXT_PUBLIC_APP_BASE: 'https://mao.591595.xyz',
        // 官网调用后端 API 的地址（与 Nginx 反向代理路径一致）
        NUXT_PUBLIC_API_BASE: '/api',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '../logs/official-site-error.log',
      out_file: '../logs/official-site-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
