module.exports = {
  apps: [
    {
      name: '3d-lms-api',
      script: 'dist/src/index.js',
      cwd: './server',
      instances: 2,
      exec_mode: 'cluster',
      wait_ready: true,
      listen_timeout: 10000,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '../logs/api-error.log',
      out_file: '../logs/api-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: '3d-lms-queue-worker',
      script: 'npm',
      args: 'run start:worker',
      cwd: './server',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '../logs/queue-worker-error.log',
      out_file: '../logs/queue-worker-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
