/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AISprite: typeof import('./components/AISprite.vue')['default']
    AssetCard: typeof import('./components/AssetCard.vue')['default']
    AssetDetailsDrawer: typeof import('./components/AssetDetailsDrawer.vue')['default']
    BaseCard: typeof import('./components/BaseCard.vue')['default']
    CourseCard: typeof import('./components/CourseCard.vue')['default']
    CreateTeamDialog: typeof import('./components/CreateTeamDialog.vue')['default']
    DiscussionCard: typeof import('./components/DiscussionCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExploreGroupsDialog: typeof import('./components/ExploreGroupsDialog.vue')['default']
    FileDropZone: typeof import('./components/FileDropZone.vue')['default']
    GroupDetailDialog: typeof import('./components/GroupDetailDialog.vue')['default']
    InvitationDialog: typeof import('./components/InvitationDialog.vue')['default']
    MarkdownEditor: typeof import('./components/MarkdownEditor.vue')['default']
    MasonryGrid: typeof import('./components/MasonryGrid.vue')['default']
    ModelViewer: typeof import('./components/ModelViewer.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    PublishWorkDialog: typeof import('./components/PublishWorkDialog.vue')['default']
    RoadmapCard: typeof import('./components/RoadmapCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeHtml: typeof import('./components/SafeHtml.vue')['default']
    ShowcaseCard: typeof import('./components/ShowcaseCard.vue')['default']
    SpriteChatArea: typeof import('./components/aiSprite/SpriteChatArea.vue')['default']
    SpriteSidebar: typeof import('./components/aiSprite/SpriteSidebar.vue')['default']
    StatCard: typeof import('./components/StatCard.vue')['default']
    TaskAddDialog: typeof import('./components/TaskAddDialog.vue')['default']
    TaskCard: typeof import('./components/TaskCard.vue')['default']
    TaskDetailDrawer: typeof import('./components/TaskDetailDrawer.vue')['default']
    TeamCard: typeof import('./components/TeamCard.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    UserProfileDialog: typeof import('./components/UserProfileDialog.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
